baseURL = "https://gurmandeep.in"
languageCode = "en-us"
title = "Gurmandeep Singh"
theme = "hugo-uno"


contentdir = "content"
publishdir = "public"
builddrafts = false

canonifyurls = true

author = "Fredrik Loch"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."


[indexes]
   category = "categories"
   tag = "tags"
[Params]
  AuthorName = "Fredrik"
  github = "gurmandeep"
  twitter = "iamgurmandeep"
  email = "gsings.singh@gmail.com"
  description = "Love to Code"
  cv = "/resume.pdf"

  linkedin = "iamgurmandeep"
  facebook = "iamgurmandeep"
  cover = "/images/background-cover.jpg"
  logo = "/logo-1.jpg"

